### ISSUE TITLE
Question: Set cookie expiration date?

### ISSUE THREAD

**Issue by NathanielGTAG** [leonjza/trauth#18]
Hi,

I am sorry if this is already said somewhere but I can not seem to find if it is possible to set the cookie expiration date through the middleware?

Thanks,

**Comment by leonjza** [comment]
It's currently [hardcoded](https://github.com/leonjza/trauth/blob/v1.6.5/config.go#L85), but definitely needs to become a config option. It needs to be in [seconds though](https://github.com/gorilla/sessions/blob/v1.3.0/options_go111.go#L14), so I guess the config option should become a "seconds in the future" kind of thing?

**Comment by NathanielGTAG** [comment]
Yeah something like that!
