### ISSUE TITLE
Question: use case Kubernetes environment with multiple domains and htpasswd files

### ISSUE THREAD

**Issue by JamborJan** [leonjza/trauth#5]
First of all thanks for creating such a great tool.

I have a use case where I'm running a Kubernetes cluster with different namespaces that have configured different ingress with different domains. Traefik is currently using a different `.htpasswd` file mounted via secrets for each namespace. This is accomplished via annotations on the namespace level.

Is it possible to have multiple domains and `.htpasswd` files with trauth? Or would it be required to spin up a trauth instance for every namespace in that case?

Thanks for your help.

**Comment by leonjza** [comment]
Right now, without any code changes a trauth instance only knows about one .htpasswd and domain. We could add the ability to have a domain -> passwd file mapping though.

**Comment by leonjza** [comment]
I know this is an ancient issue, but I just converted this to a plugin that will make this use case super easy to implement based on labels. Checkout the plugin [here](https://plugins.traefik.io/plugins/64a53f2e498e334469bdbd28/trauth), and the example docker-compose.yml [here](https://github.com/leonjza/trauth/blob/master/docker-compose.yml).
